-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2016-11-02 21:27:42 ADT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

CREATE TABLE breaks
  (
    ID              INTEGER CONSTRAINT NNC_breaks_ID NOT NULL ,
    start_time      TIMESTAMP ,
    end_time        TIMESTAMP ,
    LENGTH          DATE ,
    worked_shift_ID INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX breaks_ID_IDX ON breaks
  (
    ID ASC
  )
  ;
  CREATE INDEX breaks_worked_shift_ID_IDX ON breaks
    ( worked_shift_ID ASC
    ) ;
ALTER TABLE breaks ADD CONSTRAINT breaks_PK PRIMARY KEY ( ID ) ;


CREATE TABLE companies
  (
    ID   INTEGER CONSTRAINT NNC_companies_ID NOT NULL ,
    name VARCHAR2 (128 CHAR)
  ) ;
CREATE UNIQUE INDEX companies_ID_IDX ON companies
  (
    ID ASC
  )
  ;
ALTER TABLE companies ADD CONSTRAINT companies_PK PRIMARY KEY ( ID ) ;


CREATE TABLE employee_locations
  (
    employee_ID INTEGER
    CONSTRAINT NNC_emp_loc_employee_ID NOT NULL ,
    location_ID INTEGER
    CONSTRAINT NNC_emp_loc_location_ID NOT NULL
  ) ;
CREATE UNIQUE INDEX employee_locations_PK_IDX ON employee_locations
  (
    location_ID ASC , employee_ID ASC
  )
  ;
  CREATE INDEX emp_loc_employee_ID_IDX ON employee_locations
    (
      employee_ID ASC
    ) ;
ALTER TABLE employee_locations ADD CONSTRAINT employee_locations_PK PRIMARY KEY ( location_ID, employee_ID ) ;


CREATE TABLE employee_positions
  (
    positions_ID INTEGER
    CONSTRAINT NNC_emp_pos_positions_ID NOT NULL ,
    employees_ID INTEGER
    CONSTRAINT NNC_emp_pos_employees_ID NOT NULL
  ) ;
CREATE UNIQUE INDEX employee_positions_PK_IDX ON employee_positions
  (
    positions_ID ASC , employees_ID ASC
  )
  ;
  CREATE INDEX emp_pos_employees_ID_IDX ON employee_positions
    (
      employees_ID ASC
    ) ;
ALTER TABLE employee_positions ADD CONSTRAINT employee_positions_PK PRIMARY KEY ( positions_ID, employees_ID ) ;


CREATE TABLE employees
  (
    ID   INTEGER CONSTRAINT NNC_employees_ID NOT NULL ,
    name VARCHAR2 (128 CHAR) ,
    companies_employee_ID CLOB ,
    companies_ID INTEGER CONSTRAINT NNC_employees_companies_ID NOT NULL ,
    manager      NUMBER CONSTRAINT NNC_employees_manager NOT NULL ,
    super_admin  NUMBER CONSTRAINT NNC_employees_super_admin NOT NULL
  ) ;
CREATE UNIQUE INDEX employees_ID_IDX ON employees
  (
    ID ASC
  )
  ;
  CREATE INDEX employees_companies_ID_IDX ON employees
    ( companies_ID ASC
    ) ;
ALTER TABLE employees ADD CONSTRAINT employees_PK PRIMARY KEY ( ID ) ;


CREATE TABLE location
  (
    ID         INTEGER CONSTRAINT NNC_location_ID NOT NULL ,
    Address    VARCHAR2 (200) ,
    company_ID INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX location_ID_IDX ON location
  (
    ID ASC
  )
  ;
  CREATE INDEX location_company_ID_IDX ON location
    ( company_ID ASC
    ) ;
ALTER TABLE location ADD CONSTRAINT location_PK PRIMARY KEY ( ID ) ;


CREATE TABLE positions
  (
    ID         INTEGER CONSTRAINT NNC_positions_ID NOT NULL ,
    name       VARCHAR2 (128 CHAR) CONSTRAINT NNC_positions_name NOT NULL ,
    company_ID INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX positions_ID_IDX ON positions
  (
    ID ASC
  )
  ;
  CREATE INDEX positions_company_ID_IDX ON positions
    ( company_ID ASC
    ) ;
ALTER TABLE positions ADD CONSTRAINT positions_PK PRIMARY KEY ( ID ) ;


CREATE TABLE scheduled_shifts
  (
    ID           INTEGER CONSTRAINT NNC_scheduled_shifts_ID NOT NULL ,
    start_time   TIMESTAMP ,
    end_time     TIMESTAMP ,
    available    NUMBER ,
    LENGTH       DATE ,
    employees_ID INTEGER ,
    location_ID  INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX scheduled_shifts_ID_IDX ON scheduled_shifts
  (
    ID ASC
  )
  ;
  CREATE INDEX scheduled_shifts_emp_ID_IDX ON scheduled_shifts
    (
      employees_ID ASC
    ) ;
  CREATE INDEX scheduled_shifts_loc_ID_IDX ON scheduled_shifts
    (
      location_ID ASC
    ) ;
ALTER TABLE scheduled_shifts ADD CONSTRAINT scheduled_shifts_PK PRIMARY KEY ( ID ) ;


CREATE TABLE worked_shifts
  (
    ID                 INTEGER CONSTRAINT NNC_worked_shifts_ID NOT NULL ,
    start_time         TIMESTAMP ,
    end_time           INTEGER ,
    LENGTH             DATE ,
    scheduled_shift_ID INTEGER ,
    employee_ID        INTEGER NOT NULL ,
    location_ID        INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX worked_shifts_ID_IDX ON worked_shifts
  (
    ID ASC
  )
  ;
  CREATE INDEX worked_shifts_scheduled_ID_IDX ON worked_shifts
    (
      scheduled_shift_ID ASC
    ) ;
  CREATE INDEX worked_shifts_employee_ID_IDX ON worked_shifts
    (
      employee_ID ASC
    ) ;
  CREATE INDEX worked_shifts_location_ID_IDX ON worked_shifts
    (
      location_ID ASC
    ) ;
ALTER TABLE worked_shifts ADD CONSTRAINT worked_shifts_PK PRIMARY KEY ( ID ) ;


ALTER TABLE breaks ADD CONSTRAINT breaks_worked_shifts_FK FOREIGN KEY ( worked_shift_ID ) REFERENCES worked_shifts ( ID ) ;

ALTER TABLE employee_locations ADD CONSTRAINT emp_loc_employees_FK FOREIGN KEY ( employee_ID ) REFERENCES employees ( ID ) ;

ALTER TABLE employee_locations ADD CONSTRAINT employee_locations_location_FK FOREIGN KEY ( location_ID ) REFERENCES location ( ID ) ;

ALTER TABLE employee_positions ADD CONSTRAINT emp_pos_employee_FK FOREIGN KEY ( employees_ID ) REFERENCES employees ( ID ) ;

ALTER TABLE employee_positions ADD CONSTRAINT emp_pos_positions_FK FOREIGN KEY ( positions_ID ) REFERENCES positions ( ID ) ;

ALTER TABLE employees ADD CONSTRAINT employees_companies_FK FOREIGN KEY ( companies_ID ) REFERENCES companies ( ID ) ;

ALTER TABLE location ADD CONSTRAINT location_companies_FK FOREIGN KEY ( company_ID ) REFERENCES companies ( ID ) ;

ALTER TABLE positions ADD CONSTRAINT positions_companies_FK FOREIGN KEY ( company_ID ) REFERENCES companies ( ID ) ;

ALTER TABLE scheduled_shifts ADD CONSTRAINT scheduled_shifts_employees_FK FOREIGN KEY ( employees_ID ) REFERENCES employees ( ID ) ;

ALTER TABLE scheduled_shifts ADD CONSTRAINT scheduled_shifts_location_FK FOREIGN KEY ( location_ID ) REFERENCES location ( ID ) ;

ALTER TABLE worked_shifts ADD CONSTRAINT worked_shifts_employees_FK FOREIGN KEY ( employee_ID ) REFERENCES employees ( ID ) ;

ALTER TABLE worked_shifts ADD CONSTRAINT worked_shifts_location_FK FOREIGN KEY ( location_ID ) REFERENCES location ( ID ) ;

ALTER TABLE worked_shifts ADD CONSTRAINT worked_shifts_scheduled_FK FOREIGN KEY ( scheduled_shift_ID ) REFERENCES scheduled_shifts ( ID ) ;

CREATE SEQUENCE breaks_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER breaks_ID_TRG BEFORE
  INSERT ON breaks FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := breaks_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE companies_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER companies_ID_TRG BEFORE
  INSERT ON companies FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := companies_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE employees_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER employees_ID_TRG BEFORE
  INSERT ON employees FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := employees_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE location_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER location_ID_TRG BEFORE
  INSERT ON location FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := location_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE positions_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER positions_ID_TRG BEFORE
  INSERT ON positions FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := positions_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE scheduled_shifts_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER scheduled_shifts_ID_TRG BEFORE
  INSERT ON scheduled_shifts FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := scheduled_shifts_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE worked_shifts_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER worked_shifts_ID_TRG BEFORE
  INSERT ON worked_shifts FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := worked_shifts_ID_SEQ.NEXTVAL;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                            20
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
