-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2016-11-10 14:38:40 AST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c




CREATE TABLE breaks
  (
    ID         INTEGER CONSTRAINT NNC_breaks_ID NOT NULL ,
    start_time TIMESTAMP ,
    end_time   TIMESTAMP ,
    LENGTH INTERVAL DAY (9) TO SECOND (0) ,
    worked_shift_ID INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX breaks_ID_IDX ON breaks
  (
    ID ASC
  )
  ;
  CREATE INDEX breaks_worked_shift_ID_IDX ON breaks
    ( worked_shift_ID ASC
    ) ;
ALTER TABLE breaks ADD CONSTRAINT breaks_PK PRIMARY KEY ( ID ) ;


CREATE TABLE companies
  (
    ID   INTEGER CONSTRAINT NNC_companies_ID NOT NULL ,
    name VARCHAR2 (128 CHAR)
  ) ;
CREATE UNIQUE INDEX companies_ID_IDX ON companies
  (
    ID ASC
  )
  ;
ALTER TABLE companies ADD CONSTRAINT companies_PK PRIMARY KEY ( ID ) ;


CREATE TABLE employee_locations
  (
    employee_ID INTEGER
    CONSTRAINT NNC_employee_locations_emp_ID NOT NULL ,
    location_ID INTEGER
    CONSTRAINT NNC_employee_locations_loc_ID NOT NULL
  ) ;
CREATE UNIQUE INDEX emp_loc_loc_ID_emp_ID_IDX ON employee_locations
  (
    location_ID ASC , employee_ID ASC
  )
  ;
  CREATE INDEX employee_locations_emp_ID_IDX ON employee_locations
    (
      employee_ID ASC
    ) ;
ALTER TABLE employee_locations ADD CONSTRAINT employee_locations_PK PRIMARY KEY ( location_ID, employee_ID ) ;


CREATE TABLE employee_positions
  (
    positions_ID INTEGER
    CONSTRAINT NNC_employee_Positions_pos_ID NOT NULL ,
    employees_ID INTEGER
    CONSTRAINT NNC_employee_Positions_emp_ID NOT NULL
  ) ;
CREATE UNIQUE INDEX employee_pos_pos_ID_emp_ID_IDX ON employee_positions
  (
    positions_ID ASC , employees_ID ASC
  )
  ;
  CREATE INDEX employee_positions_emp_ID_IDX ON employee_positions
    (
      employees_ID ASC
    ) ;
ALTER TABLE employee_positions ADD CONSTRAINT employee_positions_PK PRIMARY KEY ( positions_ID, employees_ID ) ;


CREATE TABLE employees
  (
    ID   INTEGER CONSTRAINT NNC_Employees_I_D NOT NULL ,
    name VARCHAR2 (128 CHAR) ,
    companies_employee_ID CLOB ,
    companies_ID INTEGER CONSTRAINT NNC_Employees_Companies_ID NOT NULL ,
    manager      NUMBER NOT NULL ,
    super_admin  NUMBER NOT NULL ,
    state        INTEGER NOT NULL
  ) ;
ALTER TABLE employees ADD CONSTRAINT state_constraint CHECK ( state IN (0, 1, 2)) ;
CREATE UNIQUE INDEX employees_ID_IDX ON employees ( ID ASC ) ;
  CREATE INDEX employees_companies_ID_IDX ON employees
    ( companies_ID ASC
    ) ;
ALTER TABLE employees ADD CONSTRAINT employees_PK PRIMARY KEY ( ID ) ;


CREATE TABLE location
  (
    ID         INTEGER CONSTRAINT NNC_location_ID NOT NULL ,
    Address    VARCHAR2 (200) ,
    company_ID INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX location_ID_IDX ON location
  (
    ID ASC
  )
  ;
  CREATE INDEX location_company_ID_IDX ON location
    ( company_ID ASC
    ) ;
ALTER TABLE location ADD CONSTRAINT location_PK PRIMARY KEY ( ID ) ;


CREATE TABLE positions
  (
    ID         INTEGER CONSTRAINT NNC_positions_ID NOT NULL ,
    name       VARCHAR2 (128 CHAR) CONSTRAINT NNC_positions_name NOT NULL ,
    company_ID INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX positions_ID_IDX ON positions
  (
    ID ASC
  )
  ;
  CREATE INDEX positions_company_ID_IDX ON positions
    ( company_ID ASC
    ) ;
ALTER TABLE positions ADD CONSTRAINT positions_PK PRIMARY KEY ( ID ) ;


CREATE TABLE scheduled_shifts
  (
    ID         INTEGER CONSTRAINT NNC_scheduled_shifts_ID NOT NULL ,
    start_time TIMESTAMP ,
    end_time   TIMESTAMP ,
    available  NUMBER ,
    LENGTH INTERVAL DAY (9) TO SECOND (0) ,
    employees_ID INTEGER ,
    location_ID  INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX scheduled_shifts_ID_IDX ON scheduled_shifts
  (
    ID ASC
  )
  ;
  CREATE INDEX scheduled_shifts_emp_ID_IDX ON scheduled_shifts
    (
      employees_ID ASC
    ) ;
  CREATE INDEX scheduled_shifts_loc_ID_IDX ON scheduled_shifts
    (
      location_ID ASC
    ) ;
ALTER TABLE scheduled_shifts ADD CONSTRAINT scheduled_shifts_PK PRIMARY KEY ( ID ) ;


CREATE TABLE worked_shifts
  (
    ID         INTEGER CONSTRAINT NNC_worked_shifts_ID NOT NULL ,
    start_time TIMESTAMP ,
    end_time   TIMESTAMP ,
    LENGTH INTERVAL DAY (9) TO SECOND (0) ,
    scheduled_shift_ID INTEGER ,
    employee_ID        INTEGER NOT NULL ,
    location_ID        INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX worked_shifts_ID_IDX ON worked_shifts
  (
    ID ASC
  )
  ;
  CREATE INDEX worked_shifts_shift_ID_IDX ON worked_shifts
    (
      scheduled_shift_ID ASC
    ) ;
  CREATE INDEX worked_shifts_employee_ID_IDX ON worked_shifts
    (
      employee_ID ASC
    ) ;
  CREATE INDEX worked_shifts_location_ID_IDX ON worked_shifts
    (
      location_ID ASC
    ) ;
ALTER TABLE worked_shifts ADD CONSTRAINT worked_shifts_PK PRIMARY KEY ( ID ) ;


ALTER TABLE breaks ADD CONSTRAINT breaks_worked_shifts_FK FOREIGN KEY ( worked_shift_ID ) REFERENCES worked_shifts ( ID ) ;

ALTER TABLE employee_locations ADD CONSTRAINT employee_locations_emp_FK FOREIGN KEY ( employee_ID ) REFERENCES employees ( ID ) ;

ALTER TABLE employee_locations ADD CONSTRAINT employee_locations_location_FK FOREIGN KEY ( location_ID ) REFERENCES location ( ID ) ;

ALTER TABLE employee_positions ADD CONSTRAINT employee_positions_emp_FK FOREIGN KEY ( employees_ID ) REFERENCES employees ( ID ) ;

ALTER TABLE employee_positions ADD CONSTRAINT employee_positions_pos_FK FOREIGN KEY ( positions_ID ) REFERENCES positions ( ID ) ;

ALTER TABLE employees ADD CONSTRAINT employees_companies_FK FOREIGN KEY ( companies_ID ) REFERENCES companies ( ID ) ;

ALTER TABLE location ADD CONSTRAINT location_companies_FK FOREIGN KEY ( company_ID ) REFERENCES companies ( ID ) ;

ALTER TABLE positions ADD CONSTRAINT positions_companies_FK FOREIGN KEY ( company_ID ) REFERENCES companies ( ID ) ;

ALTER TABLE scheduled_shifts ADD CONSTRAINT scheduled_shifts_employees_FK FOREIGN KEY ( employees_ID ) REFERENCES employees ( ID ) ;

ALTER TABLE scheduled_shifts ADD CONSTRAINT scheduled_shifts_location_FK FOREIGN KEY ( location_ID ) REFERENCES location ( ID ) ;

ALTER TABLE worked_shifts ADD CONSTRAINT worked_shifts_employees_FK FOREIGN KEY ( employee_ID ) REFERENCES employees ( ID ) ;

ALTER TABLE worked_shifts ADD CONSTRAINT worked_shifts_location_FK FOREIGN KEY ( location_ID ) REFERENCES location ( ID ) ;

ALTER TABLE worked_shifts ADD CONSTRAINT worked_shifts_shifts_FK FOREIGN KEY ( scheduled_shift_ID ) REFERENCES scheduled_shifts ( ID ) ;

CREATE SEQUENCE breaks_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER breaks_ID_TRG BEFORE
  INSERT ON breaks FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := breaks_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE companies_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER companies_ID_TRG BEFORE
  INSERT ON companies FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := companies_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE employees_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER employees_ID_TRG BEFORE
  INSERT ON employees FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := employees_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE location_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER location_ID_TRG BEFORE
  INSERT ON location FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := location_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE positions_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER positions_ID_TRG BEFORE
  INSERT ON positions FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := positions_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE scheduled_shifts_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER scheduled_shifts_ID_TRG BEFORE
  INSERT ON scheduled_shifts FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := scheduled_shifts_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE worked_shifts_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER worked_shifts_ID_TRG BEFORE
  INSERT ON worked_shifts FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := worked_shifts_ID_SEQ.NEXTVAL;
END;
/
